### ISSUE TITLE
Question: Why BerkeleyDB over LevelDB?

### ISSUE THREAD

**Issue by aekazitt** [ruimarinho/docker-bitcoin-core#53]
Since the 2013 change in Bitcoin-Core, the node has been changed to run on LevelDB over BerkeleyDB. Is there a particular reason, development-related or not, that this repo uses BerkeleyDB in its Alpine image? 

Is it due to Alpine image limitation?

**Comment by ruimarinho** [comment]
@aekazitt BerkeleyDB has and will continue to be the database used for the wallet. Since 2013, Bitcoin Core has changed UTXOs/indexes database format to use LevelDB instead, as it offered superior performance. I remember reading about concerns over database corruption, but I don't know if that still holds true.
