### ISSUE TITLE
which one is current stable recommended for most?

### ISSUE THREAD

**Issue by movingelectrons** [ruimarinho/docker-bitcoin-core#78]
it looks like both v 0.17 and 0.18 are marked latest, does that mean first timers should use v0.16?  ty

**Comment by victorperin** [comment]
The latest is only for 0.18. We need to fix the documentation on this.

The latest version refers to using `docker run ruimarinho/bitcoin-core` without specifying te version (like `:0.18`)

That said, I recomend first timers use the latest version (at this time 0.18) because those numbers are for bitcoin core versions, we only encapsulate it in a docker container.

**Comment by ruimarinho** [comment]
I share the same opinion as @victorperin 👍
